# ワークフローの名前
name: Build

# 起動のタイミング
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

# ジョブの定義
jobs:
  build:
    # 実行するインスタンス
    runs-on: ubuntu-latest

    # nodeのバージョン一覧
    strategy:
      matrix:
        node-version: ['14.x']

    # 各ステップの実行
    steps:

    # チェックアウト
    - uses: actions/checkout@v2

    # 使用するnodeのバージョンを指定
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    # パッケージのインストールとアプリのビルド
    - name: install and build
      run: |
        yarn
        yarn build
      env:
        CI: true
