# ワークフローの名前
name: Deploy

# 起動のタイミング
# 今回はmainブランチへのpush
on:
  push:
    branches:
      - main

# ジョブの定義
jobs:
  build:
    # 実行するインスタンス
    runs-on: ubuntu-latest

    # nodeのバージョン一覧
    strategy:
      matrix:
        node-version: ['18.x']

    # 各ステップの実行
    steps:

    # チェックアウト
    - uses: actions/checkout@v2

    - name: Setup pnpm
      uses: pnpm/action-setup@v3
      with:
        version: 8

    # 使用するnodeのバージョンを指定
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: "pnpm"

    # パッケージのインストールとアプリのビルド
    - name: install and build
      run: |
        pnpm i --frozen-lockfile
        pnpm build
      env:
        CI: true

    # gh-pagesを使って公開
    - name: publish to artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: ./dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v1
