# ワークフローの名前
name: Deploy

# 起動のタイミング
# 今回はmasterブランチへのpush
on:
  workflow_run:
    workflows:
      - build
    branches:
      - master
    types:
      - completed

# ジョブの定義
jobs:
  deploy:
    # 実行するインスタンス
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    # nodeのバージョン一覧
    strategy:
      matrix:
        node-version: ['14.x']

    # 各ステップの実行
    steps:

    # チェックアウト
    - uses: actions/checkout@v2

    # 使用するnodeのバージョンを指定
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    # パッケージのインストールとアプリのビルド
    - name: install and build
      run: |
        yarn
        yarn build
      env:
        CI: true

    # gh-pagesを使って公開
    - name: deploy
      uses: peaceiris/actions-gh-pages@v2
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./build

    - name: Create CNAME
      run: |
        echo "portfolio.isso0424.dev" >> CNAME
  
    - name: Commit
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        branch: gh-pages
        commit_message: "Create CNAME"
        commit_options: "--no-verify --signoff"
        file_pattern: CNAME
        repository: .
        commit_user_name: 絶対CNAME守るMAN
        commit_author: CNAME MAN <actions@github.com> # defaults to author of the commit that triggered the run
